"""empty message

Revision ID: 489fd9878e06
Revises: 
Create Date: 2024-02-26 02:01:08.622446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489fd9878e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Creator', 'Company'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
